echo Y | del Cvs\*.*
echo Y | rd Cvs
echo Y | del AppFrame\Cvs\*.*
echo Y | rd AppFrame\Cvs
echo Y | del Auxiliary\Cvs\*.*
echo Y | rd Auxiliary\Cvs
echo Y | del config\Cvs\*.*
echo Y | rd config\Cvs
echo Y | del Draw\Cvs\*.*
echo Y | rd Draw\Cvs
echo Y | del Input\Cvs\*.*
echo Y | rd Input\Cvs
echo Y | del Math\Cvs\*.*
echo Y | rd Math\Cvs
echo Y | del Multimedia\Cvs\*.*
echo Y | rd Multimedia\Cvs
echo Y | del Thread\Cvs\*.*
echo Y | rd Thread\Cvs
echo Y | del Timer\Cvs\*.*
echo Y | rd Timer\Cvs
echo Y | del Window\Cvs\*.*
echo Y | rd Window\Cvs
echo Y | del Ytl\Cvs\*.*
echo Y | rd Ytl\Cvs
